title: ThomasR.me
description: "✌🏻 Personal website of Thomas 'Tom' Robinson"
image: /static/img/blondtommodrawing-500.jpg

baseurl: "" # no leading slash
url: https://thomasr.me
locale: en_GB

permalink: /:title/

sass:
  style: expanded
  sourcemap: development

plugins:
  - jekyll-sitemap

exclude:
  - README.md

collections:
  outings:
    layout: default
    output: true
    slug: "/outings/:path"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
